< POWER_MODEL ID=3 NAME=25W_BALANCE >
CPU_ONLINE CORE_0 1
CPU_ONLINE CORE_1 1
CPU_ONLINE CORE_2 1
CPU_ONLINE CORE_3 1
CPU_ONLINE CORE_4 1
CPU_ONLINE CORE_5 1
FBP_POWER_GATING FBP_PG_MASK 2
TPC_POWER_GATING TPC_PG_MASK 240
GPU_POWER_CONTROL_ENABLE GPU_PWR_CNTL_EN on
CPU_A78_0 MIN_FREQ 729600
CPU_A78_0 MAX_FREQ 1497600
CPU_A78_1 MIN_FREQ 729600
CPU_A78_1 MAX_FREQ 1497600
CPU_A78_2 MIN_FREQ 729600
CPU_A78_2 MAX_FREQ 1497600
CPU_A78_3 MIN_FREQ 729600
CPU_A78_3 MAX_FREQ 1497600
CPU_A78_4 MIN_FREQ 729600
CPU_A78_4 MAX_FREQ 1497600
CPU_A78_5 MIN_FREQ 729600
CPU_A78_5 MAX_FREQ 1497600
GPU MIN_FREQ 0
GPU MAX_FREQ 816000000
GPU_POWER_CONTROL_DISABLE GPU_PWR_CNTL_DIS auto
EMC MAX_FREQ 3199000000
