<?xml version="1.0"?>
<?xml-model href="http://download.ros.org/schema/format3.xsd" schematypens="http://www.w3.org/2001/XMLSchema"?>
<package format="3">
  <name>robot_camera_components</name>
  <version>0.1.0</version>
  <description>Composable camera helper nodes for the AI robot.</description>
  <maintainer email="yaschenia@gmail.com">warxen</maintainer>
  <license>Apache-2.0</license>

  <buildtool_depend>ament_cmake</buildtool_depend>

  <depend>rclcpp</depend>
  <depend>rclcpp_components</depend>
  <depend>sensor_msgs</depend>

  <export>
    <build_type>ament_cmake</build_type>
  </export>
</package>
